version: "3"
services:
  ui_nginx:
    image: shuzon21/headphonista
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    volumes:
      - ./ui/build:/usr/share/nginx/html:ro
      - ./nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf:ro
    ports:
      - 127.0.0.1:${UI_NGINX_PORT}:80
      - 127.0.0.1:${API_NGINX_PORT}:8000
    command: sh -c 'nginx -t && nginx -g "daemon off;"'
    depends_on:
      - api
    networks:
      headphonista:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.ui
    volumes:
      - ./ui:/go/src/app/ui
    ports:
      - 127.0.0.1:${UI_PORT}:3000
    command: make run
    networks:
      headphonista:
  api:
    build:
      context: ./docker
      dockerfile: Dockerfile.api
    ports:
      - 127.0.0.1:${API_PORT}:8080
    volumes:
      - ./api/headphonista/target/scala-2.13/headphonista.jar:/var/lib/jetty/webapps
    command: java -jar /var/lib/jetty/webapps
    networks:
      headphonista:

networks:
  headphonista:

